name: Deploy Hugo to GitHub Pages

on:
  push:
    branches: [ main ]
<<<<<<< HEAD
=======
  pull_request:
    branches: [ main ]
>>>>>>> 499cc8db361728c52326465134b67889309d8850

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - name: Checkout
        uses: actions/checkout@v4
        # NO submodules parameter
=======
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
>>>>>>> 499cc8db361728c52326465134b67889309d8850

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.120.4'
          extended: true

<<<<<<< HEAD
      - name: Build with Hugo
        run: |
          hugo --minify

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
=======
      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
>>>>>>> 499cc8db361728c52326465134b67889309d8850
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
